const occupations = [
    {
      category: "Digital Marketing",
      skills: [
        "Affiliate Marketing",
        "Book & eBook Marketing",
        "Community Management",
        "Crowdfunding",
        "Display Advertising",
        "E-Commerce Marketing",
        "Email Marketing",
        "Guest Posting",
        "Influencer Marketing",
        "Local SEO",
        "Marketing Advice",
        "Marketing Strategy",
        "Mobile App Marketing",
        "Music Promotion",
        "Podcast Marketing",
        "Public Relations",
        "Search Engine Marketing (SEM)",
        "Search Engine Optimization (SEO)",
        "Social Media Advertising",
        "Social Media Marketing",
        "Text Message Marketing",
        "Video Marketing",
        "Web Analytics",
        "Web Traffic",
      ],
    },
    {
      category: "Software Development",
      skills: [
        "Front-end Development",
        "Back-end Development",
        "Full-stack Development",
        "Mobile App Development",
        "Game Development",
        "API Integration",
        "DevOps Engineering",
        "Cloud Engineering",
        "Database Management",
        "QA Testing",
        "Version Control (Git)",
        "Agile Methodology",
        "Machine Learning",
        "Artificial Intelligence",
        "Data Engineering",
        "Big Data",
        "Blockchain",
        "Cybersecurity",
        "IoT Development",
      ],
    },
    {
      category: "Graphic Design",
      skills: [
        "Logo Design",
        "UI/UX Design",
        "Web Design",
        "Illustration",
        "Brand Identity Design",
        "Print Design",
        "Packaging Design",
        "Motion Graphics",
        "Photo Editing",
        "Typography",
        "Social Media Graphics",
        "3D Modeling",
      ],
    },
    {
      category: "Writing & Content Creation",
      skills: [
        "Copywriting",
        "Technical Writing",
        "Blog Writing",
        "SEO Writing",
        "Ghostwriting",
        "Proofreading & Editing",
        "Scriptwriting",
        "Creative Writing",
        "Grant Writing",
        "Content Strategy",
        "Content Marketing",
        "Social Media Content",
      ],
    },
    {
      category: "Video & Animation",
      skills: [
        "Video Editing",
        "2D Animation",
        "3D Animation",
        "Explainer Videos",
        "Whiteboard Animation",
        "Video Marketing",
        "Motion Graphics",
        "Post Production",
        "Visual Effects (VFX)",
        "Filmmaking",
      ],
    },
  ];

  export default occupations